#!/usr/bin/env bash
#
# Configuration file for smbDecode
# ================================
#
# Usage
# -----
#
# $ ./t2plconf
#
# Defining the configurations options
# -----------------------------------
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - bitfield
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'bitfield' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for type 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for type 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - bitfield : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - check    : description
#       - radio    : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range    : description ':' min ' ' max
#       - text     : description
#
# Examples
# --------
#
#ITEMS=(
#    # An item can be specified in one line...
#    T2PSKEL_VAR1 check "" "Description of option" # No dependencies
#
#    # Or span multiple lines
#    T2PSKEL_VAR1 radio "T2PSKEL_VAR1 == 1"
#           "Description of option; \
#                   0: description of val 0; \
#                   1: description of val 1; \
#                   2: description of val 2"
#
#    T2PSKEL_SIZE range "T2PSKEL_VAR1 == 1 || T2PSKEL_VAR2 > 0"
#           "Description: 0 255" # min=0, max=255
#
#    T2PSKEL_STR text
#           "T2PSKEL_SIZE <= 5 && (T2PSKEL_VAR1 != 0 || T2PSKEL_VAR2 <= 1)"
#           "Description"
#
#    T2PSKEL_BITFIELD bitfield ""
#           "Description of option; \
#                   0x01: description of bit 0; \
#                   0x02: description of bit 1; \
#                   0x04: description of bit 2; \
#                   0x08: description of bit 3; \
#                   0x10: description of bit 4; \
#                   0x20: description of bit 5; \
#                   0x40: description of bit 6; \
#                   0x80: description of bit 7"
#)
#
# If no configuration option is available, use the value 'none'
#ITEMS=(none)
#
# Source the master t2plconf file
# source ../../scripts/t2conf/t2plconf

ITEMS=(
    SMB1_DECODE check "" "Decode SMB1 (experimental)"
    SMB_SECBLOB check "" "Decode security blob (experimental)"

    SMB2_NUM_DIALECT range "" "Number of SMB2 dialects to store: 0 255"
    SMB2_NUM_STAT    range "" "Number of unique SMB2 header status to store: 0 255"

    SMB1_NUM_DIALECT range "SMB1_DECODE == 1" "Number of SMB1 dialects to store: 0 255"
    SMB1_DIAL_MAXLEN range "SMB1_DECODE == 1" "Maximum length for SMB1 dialects: 0 255"

    SMB_NUM_FNAME range "" "Number of unique filenames to store in the flow file: 0 255"

    SMB_NATIVE_NAME_LEN range "" "Max length for Native OS and LAN Manager: 0 255"

    SMB2_SAVE_DATA check "" "Save files"
    SMB1_SAVE_DATA check "SMB1_DECODE == 1" "Save files (SMB1, experimental)"

    SMB_SAVE_AUTH check "" "Save NTLM authentications"
    SMB_AUTH_FILE text  "" "Suffix for NTLM authentications file"

    SMB_SAVE_DIR text "SMB1_SAVE_DATA == 1 || SMB2_SAVE_DATA == 1" "Folder for saved data"
    SMB_MAP_FILE text "SMB1_SAVE_DATA == 1 || SMB2_SAVE_DATA == 1" "Stores the mapping between file ID and filename"
    SMB_FILE_ID  text "SMB1_SAVE_DATA == 1 || SMB2_SAVE_DATA == 1" "Prefix for output files"

    SMB_RM_DATADIR check "SMB1_SAVE_DATA == 1 || SMB2_SAVE_DATA == 1" "Remove SMB_SAVE_DIR before starting"

    SMB_FNAME_LEN range "" "Maximum length for filenames: 0 4096"
    SMB_STRCPY_BEHAVIOR radio ""
        "Behavior when data to copy is bigger than buffer; \
            T2_STRCPY_EXIT: exit; \
            T2_STRCPY_EMPTY: return an empty buffer (\"abcdefg\" -> \"\"); \
            T2_STRCPY_TRUNC: truncate destination (\"abcdefg\" -> \"abcdef\"); \
            T2_STRCPY_ELLIPSIS: truncate dest. with an ellipsis (\"abcdefg\" -> \"abc...\")"
)

# Source the master t2plconf file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
