#!/usr/bin/env bash
#
# Extracts AS numbers and corresponding continents and countries from asn.txt

source "$(dirname "$0")/../../../scripts/t2utils.sh"

AWKF '/^[^#]/ {
    split($3, s, ",")
    print $1, $2, s[length(s)]
}' asn.txt > asn2cn.txt
