#!/usr/bin/env awk

hdr() {
    next
}

# TODO which query is the DNS zone transfer?

bitsallset($dnsStat, 0x80) {
    _flowStat = _validate_col("flowStat")
    _sip = _validate_col("srcIP;srcIP4;srcIP6", _my_srcIP)
    _dip = _validate_col("dstIP;dstIP4;dstIP6", _my_dstIP)
    if (bitsallset($_flowStat, 1)) {
        _sa = $_dip
        _da = $_sip
    } else {
        _sa = $_sip
        _da = $_dip
    }

    _n = split(unquote($dnsQname), _qry, /";"/)
    for (_i = 1; _i <= _n; _i++) {
        print utc($timeFirst), _sa, _da, _qry[_i]
    }
}
