#!/usr/bin/env awk

hdr() {
    next
}

((sshStat != 0 && strtonum($sshStat) != 0) || (nDPIclass != 0 && $nDPIclass ~ /SSH/)) && $duration > 0 && $l7BytesSnt > 0 { # && (!privip(_sip) || !privip(_dip))) {
    if (sshVersion != 0) _sshver = unquote($sshVersion)
    else _sshver = ""
    print timestamp($timeFirst), $duration, tuple2(), $l7BytesSnt, _sshver
}
