#!/usr/bin/env awk

hdr() {
    next
}

!tcp() {
    next
}

# A flows
$dir == "A" && !bitsallset($flowStat, 1) {
    aggr($srcPort, $pktsSnt, n)
}

# B flows
$dir == "A" && bitsallset($flowStat, 1) {
    aggr($dstPort, $pktsRcvd, n)
}
