#!/usr/bin/env awk

hdr() {
    next
}

!udp() {
    next
}

# A flows
$dir == "A" && !bitsallset($flowStat, 1) {
    aggr($srcPort, $l7BytesSnt, n)
}

# B flows
$dir == "A" && bitsallset($flowStat, 1) {
    aggr($dstPort, $l7BytesRcvd, n)
}
