#!/usr/bin/env bash
#
# Configuration file for ospfDecode
# =================================
#
# Usage
# -----
#
# $ ./t2plconf
#
# Defining the configurations options
# -----------------------------------
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - bitfield
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'bitfield' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for type 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for type 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - bitfield : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - check    : description
#       - radio    : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range    : description ':' min ' ' max
#       - text     : description
#
# Examples
# --------
#
#ITEMS=(
#    # An item can be specified in one line...
#    T2PSKEL_VAR1 check "" "Description of option" # No dependencies
#
#    # Or span multiple lines
#    T2PSKEL_VAR1 radio "T2PSKEL_VAR1 == 1"
#           "Description of option; \
#                   0: description of val 0; \
#                   1: description of val 1; \
#                   2: description of val 2"
#
#    T2PSKEL_SIZE range "T2PSKEL_VAR1 == 1 || T2PSKEL_VAR2 > 0"
#           "Description: 0 255" # min=0, max=255
#
#    T2PSKEL_STR text
#           "T2PSKEL_SIZE <= 5 && (T2PSKEL_VAR1 != 0 || T2PSKEL_VAR2 <= 1)"
#           "Description"
#
#    T2PSKEL_BITFIELD bitfield ""
#           "Description of option; \
#                   0x01: description of bit 0; \
#                   0x02: description of bit 1; \
#                   0x04: description of bit 2; \
#                   0x08: description of bit 3; \
#                   0x10: description of bit 4; \
#                   0x20: description of bit 5; \
#                   0x40: description of bit 6; \
#                   0x80: description of bit 7"
#)
#
# If no configuration option is available, use the value 'none'
#ITEMS=(none)
#
# Source the master t2plconf file
# source ../../scripts/t2conf/t2plconf

ITEMS=(
    OSPF_OUTPUT_HLO   check "" "Output hello messages"
    OSPF_OUTPUT_DBD   check "" "Output database description messages (routing tables)"
    OSPF_OUTPUT_MSG   check "" "Output all other messages"
    OSPF_OUTPUT_STATS check "" "Output statistics file"

    OSPF_MASK_AS_IP radio ""
        "Netmask representation; \
            0: Hexadecimal; \
            1: IPv4 address"

    OSPF_AREA_AS_IP radio ""
        "Areas representation; \
            0: Integer; \
            1: IPv4 address; \
            2: Hexadecimal"

    OSPF_LSID_AS_IP radio ""
        "Link State ID representation; \
            0: Integer; \
            1: IPv4 address"

    OSPF_TYP_STR radio ""
        "Message type representation; \
            0: Aggregated hexadecimal bitfield; \
            1: list of strings"

    OSPF_LSTYP_STR radio ""
        "LS type representation; \
            0: Integer; \
            1: String"

    OSPF_NEIGMAX range "" "Maximum number of neighbors to store: 0 255"

    OSPF_NUMTYP range "OSPF_TYP_STR == 1" "Maximum number of LS types to store: 0 255"

    OSPF_SUFFIX       text "" "Suffix for output file (statistics)"
    OSPF_HELLO_SUFFIX text "" "Suffix for output file (hello messages)"

    OSPF_DBD_SUFFIX   text "OSPF_OUTPUT_DBD == 1"
        "Suffix for output file (database description/routing tables)"

    OSPF2_MSG_SUFFIX  text "OSPF_OUTPUT_MSG == 1"
        "Suffix for output file (All other messages from OSPFv2 (Link State Request/Update/Ack))"
    OSPF3_MSG_SUFFIX  text "OSPF_OUTPUT_MSG == 1"
        "Suffix for output file (All other messages from OSPFv3 (Link State Request/Update/Ack))"
)

# Source the master t2plconf file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
