#!/usr/bin/env awk
#
# Returns true if 'val' contains 'txt' (case insensitive).
#
# Parameters:
#   - val : the value to analyze
#   - txt : the value to search for in 'val'
#
# Dependencies:
#   - None
#
# See also:
#   - contains
#   - cvalcontains
#   - cvalcontainsi
#   - rvalcontains
#   - rvalcontainsi
#   - valcontains
#   - valcontainsi
#
# Examples:
#   - tawk 'containsi($httpURL, "php")' file.txt
#   - tawk 'containsi($httpURL, "admin) { print $httpURL }' file.txt

@include "contains"

function containsi(val, txt) {
    return contains(val, txt, 1)
}
