#!/usr/bin/env awk
#
# Return true if the flow contains HTTP traffic.
#
# Parameters:
#   - None
#
# Dependencies:
#   - httpSniffer
#
# Examples:
#   - tawk 'http()' file.txt
#   - tawk 'http() { print $srcIP }' file.txt
#   - tawk 'http() { print wildcard("^http") }' file.txt

@include "hdr"
@include "_validate_col"

function http(        _c) {
    _c = _validate_col("httpStat")
    if (hdr()) return __PRIHDR__
    return strtonum($_c)
}
