#!/usr/bin/env awk
#
# Convert an IPv4 address 'ip' to hex.
#
# Parameters:
#   - ip : the IPv4 address to convert
#
# Dependencies:
#   - None
#
# See also:
#   - ip2num : convert an IP address to a number
#   - ip2str : convert an IPv4 address to string
#
# Examples:
#   - tawk '{ print ip2hex($srcIP) }' file.txt

@include "ip2num"
@include "isipnum"
@include "isipstr"

function ip2hex(ip) {
    if (!isipstr(ip) && !isipnum(ip)) {
        return ip
    } else {
        return sprintf("0x%08x", ip2num(ip))
    }
}
