#!/usr/bin/env awk
#
# Return true if 'v' is an IPv6 address.
#
# Parameters:
#   - v : the value to test
#
# Dependencies:
#   - None
#
# See also:
#   - isip
#   - isiphex
#   - isipnum
#   - isipstr
#
# Examples:
#   - tawk 'isip6($dstIP)' file.txt
#   - tawk 'isip6($srcIP) { print }' file.txt
#   - tawk '{ print isip6("::1") }' file.txt

@include "hdr"

function isip6(v) {
    return (v ~ /:/ || (__PRIHDR__ && hdr()))
}
