#!/usr/bin/env awk
#
# Return true if 'v' is an IPv4 address in numerical (int) notation.
#
# Parameters:
#   - v : the value to test
#
# Dependencies:
#   - None
#
# See also:
#   - isip
#   - isip6
#   - isiphex
#   - isipstr
#
# Examples:
#   - tawk 'isipnum($dstIP)' file.txt
#   - tawk 'isipnum($srcIP) { print }' file.txt
#   - tawk '{ print isipnum("1.2.3.4") }' file.txt

@include "hdr"

function isipnum(v) {
    return (v ~ /^[0-9]{1,10}$/ || (__PRIHDR__ && hdr()))
}
