#!/usr/bin/env awk
#
# Return true if 'v' is a number (signed, unsigned or floating point),
# false otherwise.
#
# Parameters:
#   - v : the value to test
#
# Dependencies:
#   - None
#
# See also:
#   - isfloat
#   - isint
#   - isset
#   - isuint
#
# Examples:
#   - tawk 'isnum(-4.2)   { print "true"  }' file.txt
#   - tawk 'isnum(3.)     { print "true"  }' file.txt
#   - tawk 'isnum(0.0)    { print "true"  }' file.txt
#   - tawk 'isnum(2)      { print "true"  }' file.txt
#   - tawk 'isnum(-1)     { print "true"  }' file.txt
#   - tawk 'isnum("test") { print "false" }' file.txt

@include "hdr"

function isnum(v) {
    return ((v == v + 0) || (__PRIHDR__ && hdr()))
}
