#!/usr/bin/env awk
#
# Return true if 'v' is an unsigned integer, false otherwise.
#
# Parameters:
#   - v : the value to test
#
# Dependencies:
#   - None
#
# See also:
#   - isfloat
#   - isint
#   - isnum
#   - isset
#
# Examples:
#   - tawk 'isuint(2)      { print "true"  }' file.txt
#   - tawk 'isuint(0)      { print "true"  }' file.txt
#   - tawk 'isuint(-4)     { print "false" }' file.txt
#   - tawk 'isuint(3.)     { print "false" }' file.txt
#   - tawk 'isuint(2.0)    { print "false" }' file.txt
#   - tawk 'isuint("test") { print "false" }' file.txt

@include "hdr"

function isuint(v) {
    return (v ~ /^(0|[1-9][0-9]*)$/) || (__PRIHDR__ && hdr())
}
