#!/usr/bin/env awk
#
# Return true if 'ip' is a loopback address.
#
# Loopback addresses:
#   IPv4: 127.0.0.0/8
#   IPv6: ::1
#
# Parameters:
#   - ip : the IP address to test
#
# Dependencies:
#   - None
#
# Examples:
#   - tawk 'loopback($dstIP)' file.txt
#   - tawk '!loopback($dstIP) { print }' file.txt

@include "hdr"
@include "ip6compress"
@include "ipinnet"
@include "isip"

function loopback(ip) {
    if (hdr()) return __PRIHDR__
    if (isip(ip)) {
        return ipinnet(ip, "127.0.0.0/8")
    } else {
        return ip6compress(ip) == "::1"
    }
}
