#!/usr/bin/env awk
#
# Remove leading spaces from a string 's'.
#
# Parameters:
#   - s : the string to strip
#
# Dependencies:
#   - None
#
# See also:
#   - rstrip
#   - strip
#   - chomp
#   - quote
#   - unquote
#
# Examples:
#   - tawk '{ print lstrip("  str  ") }' file.txt

function lstrip(s) {
    gsub(/^\s*/, "", s) # remove leading spaces
    return s
}
