#!/usr/bin/env awk
#
# Return the minimum value between 'a' and 'b'.
#
# Parameters:
#   - a : the first value
#   - b : the second value
#
# Dependencies:
#   - None
#
# See also:
#   - max
#   - max2
#   - max3
#   - min
#   - min3
#
# Examples:
#   - tawk '{ print min2(1, 2) }' file.txt

function min2(a, b) {
    return (a < b ? a : b)
}
