#!/usr/bin/env awk
#
# Return the minimum value between 'a', 'b' and 'c'.
#
# Parameters:
#   - a : the first value
#   - b : the second value
#   - c : the third value
#
# Dependencies:
#   - None
#
# See also:
#   - min
#   - min2
#   - max
#   - max2
#   - max3
#
# Examples:
#   - tawk '{ print min3(1, 2, 3) }' file.txt

function min3(a, b, c) {
    return (a < b ? (a < c ? a : c) : (b < c ? b : c))
}
