#!/usr/bin/env awk
#
# Print the string 's' in bold with an added newline.
# If 'n' is set, the trailing newline is omitted.
#
# Parameters:
#   - s: the string to print
#   - n: omit the trailing newline if 'n > 0'
#
# Dependencies:
#   - None
#
# See also:
#   - printerr
#   - printinf
#   - printok
#   - printwrn
#
# Examples:
#   - tawk '$pktsSnt == 42 { printbold("42 packets sent") }' file.txt
#   - tawk '{ printbold("Hello ", 1); printbold("World") }' file.txt

function printbold(s, n,        _n) {
    _n = (n ? "" : "\n")
    printf "\033[1m%s\033[0m%s", s, _n
}
