#!/usr/bin/env awk
#
# Return true if the protocol number is equal to 46 (RSVP).
#
# Parameters:
#   - [p] : the protocol to test [default: $l4Proto]
#
# Dependencies:
#   - basicFlow
#
# See also:
#   - proto
#   - proto2str : string representation of a protocol
#   - icmp      : alias for proto(1)
#   - igmp      : alias for proto(2)
#   - tcp       : alias for proto(6)
#   - udp       : alias for proto(17)
#   - gre       : alias for proto(47)
#   - esp       : alias for proto(50)
#   - ah        : alias for proto(51)
#   - icmp6     : alias for proto(58)
#   - sctp      : alias for proto(132)
#
# Examples:
#   - tawk 'rsvp()' file.txt
#   - tawk 'rsvp() { print $srcIP }' file.txt
#   - tawk 'rsvp($l4Proto)' file.txt
#   - tawk 'rsvp($l4Proto) { print $srcIP }' file.txt

@include "hdr"
@include "proto"

function rsvp(p) {
    if (hdr()) return __PRIHDR__
    if (p) return p == 46
    else return proto(46)
}
