#!/usr/bin/env awk
#
# Return true if one item of the repetitive value 'val' is 'item' (case insensitive).
#
# Parameters:
#   - val  : the value to analyze
#   - item : the value to search for in 'val'
#
# Dependencies:
#   - None
#
# See also:
#   - contains
#   - containsi
#   - cvalcontains
#   - cvalcontainsi
#   - rvalcontains
#   - valcontains
#   - valcontainsi
#
# Examples:
#   - tawk 'rvalcontainsi($vlanID, 20)' file.txt
#   - tawk 'rvalcontainsi("str1;STR2;str3", "str2") { print }' file.txt

@include "rvalcontains"

function rvalcontainsi(val, item) {
    return rvalcontains(val, item, 1)
}
