#!/usr/bin/env awk
#
# Return true if one item of the repetitive value 'val' is 'item'.
# If 'ign' is 1, perform a case insensitive comparison.
#
# Parameters:
#   - val   : the value to analyze
#   - item  : the value to search for in 'val'
#   - [ign] : if set and != 0, perform a case insensitive comparison
#
# Dependencies:
#   - None
#
# See also:
#   - contains
#   - containsi
#   - cvalcontains
#   - cvalcontainsi
#   - rvalcontainsi
#   - valcontains
#   - valcontainsi
#
# Examples:
#   - tawk 'rvalcontains($vlanID, 20)' file.txt
#   - tawk 'rvalcontains("str1;str2;str3", "str2") { print }' file.txt

@include "valcontains"

function rvalcontains(val, item, ign) {
    return valcontains(val, ";", item, ign)
}
