#!/usr/bin/env awk
#
# Return true if the protocol number is equal to 132 (SCTP).
#
# Parameters:
#   - [p] : the protocol to test [default: $l4Proto]
#
# Dependencies:
#   - basicFlow
#
# See also:
#   - proto
#   - proto2str : string representation of a protocol
#   - icmp      : alias for proto(1)
#   - igmp      : alias for proto(2)
#   - tcp       : alias for proto(6)
#   - udp       : alias for proto(17)
#   - rsvp      : alias for proto(46)
#   - gre       : alias for proto(47)
#   - esp       : alias for proto(50)
#   - ah        : alias for proto(51)
#   - icmp6     : alias for proto(58)
#
# Examples:
#   - tawk 'sctp()' file.txt
#   - tawk 'sctp() { print $srcIP }' file.txt
#   - tawk 'sctp($l4Proto)' file.txt
#   - tawk 'sctp($l4Proto) { print $srcIP }' file.txt

@include "hdr"
@include "proto"

function sctp(p) {
    if (hdr()) return __PRIHDR__
    if (p) return p == 132
    else return proto(132)
}
