#!/usr/bin/env awk
#
# Return true if one of the source MAC address(es) is equal to 'mac'.
# If 'mac' is omitted, return the source MAC address(es).
#
# Parameters:
#   - [m] : the MAC address to filter
#
# Dependencies:
#   - macRecorder
#
# See also:
#   - dether
#   - dmac
#   - ether
#   - mac
#   - smac: alias for sether
#
# Examples:
#   - tawk 'sether("00:11:22:33:44:55")' file.txt
#   - tawk '{ print sether() }' file.txt

@include "smac"

function sether(m) {
    return smac(m)
}
