#!/usr/bin/env awk
#
# Return true if 'val1' is not equal to 'val2' (case insensitive).
#
# Parameters:
#   - val1 : the first value
#   - val2 : the second value
#
# Dependencies:
#   - None
#
# See also:
#   - streq
#   - streqi
#   - strneq
#   - strisempty
#
# Examples:
#   - tawk 'strneqi($srcIP, $dstIP)' file.txt
#   - tawk 'strneqi("abc", "ABc") { print }' file.txt

@include "strneq"

function strneqi(val1, val2) {
    return strneq(val1, val2, 1)
}
