#!/usr/bin/env bash
#
# Configuration file for dnsDecode
# ================================
#
# Usage
# -----
#
# $ ./t2plconf
#
# Defining the configurations options
# -----------------------------------
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - bitfield
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'bitfield' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for type 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for type 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - bitfield : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - check    : description
#       - radio    : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range    : description ':' min ' ' max
#       - text     : description
#
# Examples
# --------
#
#ITEMS=(
#    # An item can be specified in one line...
#    T2PSKEL_VAR1 check "" "Description of option" # No dependencies
#
#    # Or span multiple lines
#    T2PSKEL_VAR1 radio "T2PSKEL_VAR1 == 1"
#           "Description of option; \
#                   0: description of val 0; \
#                   1: description of val 1; \
#                   2: description of val 2"
#
#    T2PSKEL_SIZE range "T2PSKEL_VAR1 == 1 || T2PSKEL_VAR2 > 0"
#           "Description: 0 255" # min=0, max=255
#
#    T2PSKEL_STR text
#           "T2PSKEL_SIZE <= 5 && (T2PSKEL_VAR1 != 0 || T2PSKEL_VAR2 <= 1)"
#           "Description"
#
#    T2PSKEL_BITFIELD bitfield ""
#           "Description of option; \
#                   0x01: description of bit 0; \
#                   0x02: description of bit 1; \
#                   0x04: description of bit 2; \
#                   0x08: description of bit 3; \
#                   0x10: description of bit 4; \
#                   0x20: description of bit 5; \
#                   0x40: description of bit 6; \
#                   0x80: description of bit 7"
#)
#
# If no configuration option is available, use the value 'none'
#ITEMS=(none)
#
# Source the master t2plconf file
# source ../../scripts/t2conf/t2plconf

ITEMS=(
    DNS_MODE radio ""
        "Information to output; \
            0: Only aggregated header info; \
            1: +Req Content Info; \
            2: +Answer Records; \
            3: +AUX records; \
            4: +Add records"

    DNS_HEXON check "" "Output hexadecimal flags"

    DNS_HDRMD radio ""
        "Format for header flags, opcode and return code; \
                    0: Bitfield; \
                    1: Integer; \
                    2: String"

    DNS_TYPE radio ""
        "Query/Answer type; \
            0: Numeric; \
            1: String"

    DNS_AGGR check "" "Aggregate request/answer records"

    DNS_QRECMAX range "" "Max # of query records / flow: 1 255"
    DNS_ARECMAX range "" "Max # of answer records / flow: 1 255"

    DNS_WHO check "" "Output country and organization of DNS reply address"

    DNS_MAL_TEST radio ""
        "Test for malware; \
            0: Do not test for malware; \
            1: Mal test once @ flow terminated; \
            2: Mal test @ L4 callback, pcap ops"

    DNS_MAL_TYPE radio "DNS_MAL_TEST == 1"
        "Malware type format; \
            0: Code; \
            1: String"

    #DNS_MAL_DOMAIN radio "DNS_MAL_TEST == 1" "Blacklist to use; 0: IP addresses; 1: domain names"
)

# Source the master t2plconf file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
