#!/usr/bin/env awk
#
# Bytes - default input
#
# Dependencies:
#   - basicStats
#
# Example:
#   - tawk '{ print byt() }' file

@include "hdr"
@include "_validate_col"

function byt(        _c) {
    _c = _validate_col("l7BytesRcvd;l4BytesRcvd;l3BytesRcvd;l2BytesRcvd", _my_bytesRcvd)
    if (hdr()) return "Bytes"
    return $_c
}
