#!/usr/bin/env awk
#
# Input Bytes
#
# Dependencies:
#   - basicStats
#
# Example:
#   - tawk '{ print ibyt() }' file

@include "hdr"
@include "_validate_col"

function ibyt(        _c) {
    _c = _validate_col("l7BytesRcvd;l4BytesRcvd;l3BytesRcvd;l2BytesRcvd", _my_bytesRcvd)
    if (hdr()) return "In Byte"
    return $_c
}
