#!/usr/bin/env awk
#
# Packets - default input
#
# Dependencies:
#   - basicStats
#
# Example:
#   - tawk '{ print pkt() }' file

@include "hdr"
@include "_validate_col"

function pkt(        _c) {
    _c = _validate_col("pktsRcvd", _my_pktsRcvd)
    if (hdr()) return "Packets"
    return $_c
}
