#!/usr/bin/env bash
#
# Configuration file for bgpDecode
# ================================
#
# Usage
# -----
#
# $ ./t2plconf
#
# Defining the configurations options
# -----------------------------------
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - bitfield
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'bitfield' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for type 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for type 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - bitfield : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - check    : description
#       - radio    : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range    : description ':' min ' ' max
#       - text     : description
#
# Examples
# --------
#
#ITEMS=(
#    # An item can be specified in one line...
#    T2PSKEL_VAR1 check "" "Description of option" # No dependencies
#
#    # Or span multiple lines
#    T2PSKEL_VAR1 radio "T2PSKEL_VAR1 == 1"
#           "Description of option; \
#                   0: description of val 0; \
#                   1: description of val 1; \
#                   2: description of val 2"
#
#    T2PSKEL_SIZE range "T2PSKEL_VAR1 == 1 || T2PSKEL_VAR2 > 0"
#           "Description: 0 255" # min=0, max=255
#
#    T2PSKEL_STR text
#           "T2PSKEL_SIZE <= 5 && (T2PSKEL_VAR1 != 0 || T2PSKEL_VAR2 <= 1)"
#           "Description"
#
#    T2PSKEL_BITFIELD bitfield ""
#           "Description of option; \
#                   0x01: description of bit 0; \
#                   0x02: description of bit 1; \
#                   0x04: description of bit 2; \
#                   0x08: description of bit 3; \
#                   0x10: description of bit 4; \
#                   0x20: description of bit 5; \
#                   0x40: description of bit 6; \
#                   0x80: description of bit 7"
#)
#
# If no configuration option is available, use the value 'none'
#ITEMS=(none)
#
# Source the master t2plconf file
# source ../../scripts/t2conf/t2plconf

ITEMS=(
    BGP_DEBUG check "" "Activate debug output"

    BGP_IP_FORMAT radio ""
        "Representation of IP addresses; \
                0: hex; \
                1: IP; \
                2: int"

    BGP_AS_FORMAT radio ""
        "Representation of AS numbers; \
                0: ASPLAIN; \
                1: ASDOT; \
                2: ASDOT+"

    BGP_NOTIF_FORMAT radio ""
        "Representation of BGP notifications; \
            0: uint8; \
            1: string (code only)"
    #       2: string (code and subcode)"

    BGP_TRAD_BOGONS check "" "Flag traditional bogons"

    BGP_OUTPUT_RT check "" "Output routing tables"

    BGP_ORIG_ID check
        "BGP_OUTPUT_RT == 1"
        "Output originator id"

    BGP_AGGR check
        "BGP_OUTPUT_RT == 1"
        "Output aggregator"

    BGP_CLUSTER check
        "BGP_OUTPUT_RT == 1"
        "Output cluster list"

    BGP_COMMUNITIES check
        "BGP_OUTPUT_RT == 1"
        "Output communities"

    BGP_AS_PATH_AGGR check
        "BGP_OUTPUT_RT == 1"
        "Aggregate repetitions of the same AS"

    BGP_MASK_FORMAT radio
        "BGP_OUTPUT_RT == 1"
        "Netmask representation; \
            0: hex; \
            1: IP; \
            2: int"
    #        3: int (cidr)"

    BGP_RT check "" "Store routing information in a hashtable"
    BGP_DEBUG_RT check
        "BGP_RT == 1"
        "Activate debug output for routing information"
    BGP_RT_MASK check "BGP_RT == 1" "Use the mask as part of the key for the routing table"

    BGP_ASIZE range "" "Size of arrays for update records: 1 UINT16_MAX"

    BGP_SUFFIX text
           "BGP_OUTPUT_RT == 1"
           "Suffix to use for routing tables information"

    BGP_MOAS_SUFFIX text "" "Suffix for MOAS information"
    BGP_ANOM_SUFFIX text "" "Suffix for anomaly file"
)

# Source the master t2plconf file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
