#!/usr/bin/env bash
#
# Configuration file for jsonSink
# ===============================
#
# Usage
# -----
#
# $ ./t2plconf
#
# Defining the configurations options
# -----------------------------------
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - bitfield
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'bitfield' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for type 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for type 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - bitfield : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - check    : description
#       - radio    : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range    : description ':' min ' ' max
#       - text     : description
#
# Examples
# --------
#
#ITEMS=(
#    # An item can be specified in one line...
#    T2PSKEL_VAR1 check "" "Description of option" # No dependencies
#
#    # Or span multiple lines
#    T2PSKEL_VAR1 radio "T2PSKEL_VAR1 == 1"
#           "Description of option; \
#                   0: description of val 0; \
#                   1: description of val 1; \
#                   2: description of val 2"
#
#    T2PSKEL_SIZE range "T2PSKEL_VAR1 == 1 || T2PSKEL_VAR2 > 0"
#           "Description: 0 255" # min=0, max=255
#
#    T2PSKEL_STR text
#           "T2PSKEL_SIZE <= 5 && (T2PSKEL_VAR1 != 0 || T2PSKEL_VAR2 <= 1)"
#           "Description"
#
#    T2PSKEL_BITFIELD bitfield ""
#           "Description of option; \
#                   0x01: description of bit 0; \
#                   0x02: description of bit 1; \
#                   0x04: description of bit 2; \
#                   0x08: description of bit 3; \
#                   0x10: description of bit 4; \
#                   0x20: description of bit 5; \
#                   0x40: description of bit 6; \
#                   0x80: description of bit 7"
#)
#
# If no configuration option is available, use the value 'none'
#ITEMS=(none)
#
# Source the master t2plconf file
# source ../../scripts/t2conf/t2plconf

ITEMS=(
    JSON_ROOT_NODE            check ""                    "Add a root node (array)"
    JSON_SUPPRESS_EMPTY_ARRAY check ""                    "Output empty fields"
    JSON_NO_SPACES            check ""                    "Suppress unnecessary spaces"
    JSON_GZ_COMPRESS          check ""                    "Compress the output using gzip"
    JSON_SOCKET_ON            radio ""                    "Output; 0: file; 1: socket"
    JSON_SOCKET_ADDR          text  "JSON_SOCKET_ON == 1" "Address of the socket"
    JSON_SOCKET_PORT          range "JSON_SOCKET_ON == 1" "Address of the socket: 0 65535"
    JSON_SPLIT                check "JSON_SOCKET_ON == 0" "Split the output (Tranalyzer -W option)"
    JSON_SUFFIX               text  "JSON_SOCKET_ON == 0" "Suffix for output file"
    JSON_SELECT               check ""                    "Use JSON_SELECT_FILE to only output specific fields"
    JSON_SELECT_FILE          text  "JSON_SELECT == 1"    "Filename of the field selector (one column name per line)"
    JSON_BUFFER_SIZE          range ""                    "Maximum size of buffer: 0 4294967295"
)

# Source the master t2plconf file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
