#!/usr/bin/env bash
#
# Configuration file for sslDecode
# ================================
#
# Usage
# -----
#
# $ ./t2plconf
#
# Defining the configurations options
# -----------------------------------
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - bitfield
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'bitfield' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for type 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for type 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - bitfield : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - check    : description
#       - radio    : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range    : description ':' min ' ' max
#       - text     : description
#
# Examples
# --------
#
#ITEMS=(
#    # An item can be specified in one line...
#    T2PSKEL_VAR1 check "" "Description of option" # No dependencies
#
#    # Or span multiple lines
#    T2PSKEL_VAR1 radio "T2PSKEL_VAR1 == 1"
#           "Description of option; \
#                   0: description of val 0; \
#                   1: description of val 1; \
#                   2: description of val 2"
#
#    T2PSKEL_SIZE range "T2PSKEL_VAR1 == 1 || T2PSKEL_VAR2 > 0"
#           "Description: 0 255" # min=0, max=255
#
#    T2PSKEL_STR text
#           "T2PSKEL_SIZE <= 5 && (T2PSKEL_VAR1 != 0 || T2PSKEL_VAR2 <= 1)"
#           "Description"
#
#    T2PSKEL_BITFIELD bitfield ""
#           "Description of option; \
#                   0x01: description of bit 0; \
#                   0x02: description of bit 1; \
#                   0x04: description of bit 2; \
#                   0x08: description of bit 3; \
#                   0x10: description of bit 4; \
#                   0x20: description of bit 5; \
#                   0x40: description of bit 6; \
#                   0x80: description of bit 7"
#)
#
# If no configuration option is available, use the value 'none'
#ITEMS=(none)
#
# Source the master t2plconf file
# source ../../scripts/t2conf/t2plconf

ITEMS=(
    SSL_ANALYZE_OVPN check "" "Analyze OpenVPN (Experimental)"
    SSL_ANALYZE_QUIC check "" "Analyze TLS 1.3 client/server hello in QUIC initial packets"

    SSL_REC_VER check ""
        "Output the list and number of record versions"
    SSL_MAX_REC_VER range "SSL_REC_VER == 1"
        "Maximum number of record versions to store: 0 255"

    SSL_HAND_VER check ""
        "Output the list and number of handshake versions"
    SSL_MAX_HAND_VER range "SSL_HAND_VER == 1"
        "Maximum number of handshake versions to store: 0 255"

    SSL_EXT_LIST check ""
        "Output the list and number of extensions"
    SSL_MAX_EXT range "SSL_EXT_LIST == 1"
        "Maximum number of extensions to store: 0 255"

    SSL_SUPP_VER check ""
        "Output the list and number of supported versions"
    SSL_MAX_SUPP_VER range "SSL_SUPP_VER == 1"
        "Maximum number of supported versions to store: 0 255"

    SSL_SIG_ALG check ""
        "Output the list and number of signature hash algorithms"
    SSL_MAX_SIG_ALG range "SSL_SIG_ALG == 1"
        "Maximum number of signature hash algorithms to store: 0 255"

    SSL_EC check ""
        "Output the list and number of elliptic curves"
    SSL_MAX_EC range "SSL_EC == 1"
        "Maximum number of elliptic curves to store: 0 255"

    SSL_EC_FORMATS check ""
        "Output the list and number of elliptic curve formats"
    SSL_MAX_EC_FORMATS range "SSL_EC_FORMATS == 1"
        "Maximum number of elliptic curve formats to store: 0 255"

    SSL_ALPN_LIST check ""
        "Output the list and number of protocols (ALPN)"
    SSL_ALPS_LIST check ""
        "Output the list and number of protocols (ALPS)"
    SSL_NPN_LIST check ""
        "Output the list and number of protocols (NPN)"
    SSL_MAX_PROTO range "SSL_ALPN_LIST == 1 || SSL_ALPS_LIST == 1 || SSL_NPN_LIST == 1"
        "Maximum number of protocols (ALPN/ALPS/NPN) to store: 0 255"
    SSL_PROTO_LEN range "SSL_JA4 == 1 || SSL_JA4_O == 1 || SSL_JA4_R == 1 || SSL_JA4_RO == 1 || SSL_ALPN_LIST == 1 || SSL_ALPS_LIST == 1 || SSL_NPN_LIST == 1"
        "Maximum number of characters per protocol (ALPN/ALPS/NPN): 0 255"

    SSL_CIPHER_LIST check ""
        "Output the list and number of supported ciphers"
    SSL_MAX_CIPHER range "SSL_CIPHER_LIST == 1"
        "Maximum number of ciphers to store: 0 255"

    SSL_ANALYZE_CERT check "" "Analyze certificates"

    SSL_CERT_SERIAL check "SSL_ANALYZE_CERT == 1"
        "Print the certificate serial number"
    SSL_CERT_FINGPRINT radio "SSL_ANALYZE_CERT == 1"
        "Extraction of certificate fingerprint; \
            0: no certificate fingerprint; \
            1: SHA1; \
            2: MD5"
    SSL_CERT_VALIDITY check "SSL_ANALYZE_CERT == 1"
        "Print the certificate validity (Valid from/to)"
    SSL_CERT_SIG_ALG check "SSL_ANALYZE_CERT == 1"
        "Print the certificate signature algorithm"
    SSL_CERT_PUBKEY_ALG check "SSL_ANALYZE_CERT == 1"
        "Print the certificate public key algorithm"
    SSL_CERT_ALG_NAME_LONG radio "SSL_ANALYZE_CERT == 1"
        "Algorithm names; \
            0: Short names; \
            1: Long names"
    SSL_CERT_PUBKEY_TS check "SSL_ANALYZE_CERT == 1"
        "Print the certificate public key type and size"

    SSL_CERT_SUBJECT radio "SSL_ANALYZE_CERT == 1"
        "Certificate subject representation; \
            0: no information about the certificate subject; \
            1: Whole subject as one string; \
            2: Selected fields only"
    SSL_CERT_ISSUER radio "SSL_ANALYZE_CERT == 1"
        "Certificate issuer representation; \
            0: no information about the certificate subject; \
            1: Whole subject as one string; \
            2: Selected fields only"

    SSL_CERT_COMMON_NAME check
        "SSL_ANALYZE_CERT == 1 && (SSL_CERT_SUBJECT == 2 || SSL_CERT_ISSUER == 2)"
        "Print the common name of the issuer/subject"
    SSL_CERT_ORGANIZATION check
        "SSL_ANALYZE_CERT == 1 && (SSL_CERT_SUBJECT == 2 || SSL_CERT_ISSUER == 2)"
        "Print the organization name of the issuer/subject"
    SSL_CERT_ORG_UNIT check
        "SSL_ANALYZE_CERT == 1 && (SSL_CERT_SUBJECT == 2 || SSL_CERT_ISSUER == 2)"
        "Print the organizational unit name of the issuer/subject"
    SSL_CERT_LOCALITY check
        "SSL_ANALYZE_CERT == 1 && (SSL_CERT_SUBJECT == 2 || SSL_CERT_ISSUER == 2)"
        "Print the locality name of the issuer/subject"
    SSL_CERT_STATE check
        "SSL_ANALYZE_CERT == 1 && (SSL_CERT_SUBJECT == 2 || SSL_CERT_ISSUER == 2)"
        "Print the state or province of the issuer/subject"
    SSL_CERT_COUNTRY check
        "SSL_ANALYZE_CERT == 1 && (SSL_CERT_SUBJECT == 2 || SSL_CERT_ISSUER == 2)"
        "Print the country of the issuer/subject"

    SSL_DETECT_TOR check
        "SSL_ANALYZE_CERT == 1 && (SSL_CERT_SUBJECT > 0 || SSL_CERT_ISSUER > 0)"
        "Detect likely Tor connections"

    # Certificates
    SSL_SAVE_CERT check "SSL_ANALYZE_CERT == 1" "Save certificates"
    SSL_RM_CERTDIR check
        "SSL_ANALYZE_CERT == 1 && SSL_SAVE_CERT == 1"
        "Remove SSL_CERT_PATH before starting"
    SSL_CERT_NAME_FINDEX check
        "SSL_ANALYZE_CERT == 1 && SSL_SAVE_CERT == 1"
        "Prepend the flowIndex to the certificate name"
    SSL_CERT_PATH text
        "SSL_ANALYZE_CERT == 1 && SSL_SAVE_CERT == 1"
        "Folder for saved certificates"  # TODO dir chooser
    SSL_CERT_EXT text
        "SSL_ANALYZE_CERT == 1 && SSL_SAVE_CERT == 1"
        "Extension for saved certificates"

    SSL_BLIST check
        "SSL_ANALYZE_CERT == 1 && (SSL_SAVE_CERT == 1 || SSL_CERT_FINGPRINT == 1)"
        "Search for blacklisted certificates"
    SSL_BLIST_LEN range
        "SSL_ANALYZE_CERT == 1 && (SSL_SAVE_CERT == 1 || SSL_CERT_FINGPRINT == 1) && SSL_BLIST == 1"
        "Max length for blacklist descriptions: 0 255"
    SSL_JA4    check "" "Output JA4/JA4S fingerprints"
    SSL_JA4_O  check "" "Output JA4/JA4S_o fingerprints (original order)"
    SSL_JA4_R  check "" "Output JA4/JA4S_r fingerprints (raw)"
    SSL_JA4_RO check "" "Output JA4/JA4S_ro fingerprints (raw, original order)"
    SSL_JA4_STR_LEN range "(SSL_JA4_O == 1 || SSL_JA4_RO == 1)"
        "Max length for uncompressed JA4/JA4S signatures (JA4/JA4S_r, JA4/JA4S_ro): 1 UINT16_MAX"
    SSL_JA4_DLEN range
        "SSL_JA4 == 1"
        "Max length for JA4/JA4S descriptions: 1 UINT16_MAX"
    SSL_JA3 check
        "SSL_ANALYZE_CERT == 1 && (SSL_SAVE_CERT == 1 || SSL_CERT_FINGPRINT == 1)"
        "Output JA3 fingerprints (hash and description)"
    SSL_JA3_STR check
        "SSL_ANALYZE_CERT == 1 && (SSL_SAVE_CERT == 1 || SSL_CERT_FINGPRINT == 1) && SSL_JA3 == 1"
        "Also output JA3 fingerprints before hashing"
    SSL_JA3_DLEN range
        "SSL_ANALYZE_CERT == 1 && (SSL_SAVE_CERT == 1 || SSL_CERT_FINGPRINT == 1) && SSL_JA3 == 1"
        "Max length for JA3 descriptions: 1 UINT16_MAX"
    SSL_JA3_STR_LEN range
        "SSL_ANALYZE_CERT == 1 && (SSL_SAVE_CERT == 1 || SSL_CERT_FINGPRINT == 1) && SSL_JA3 == 1"
        "Max length for uncompressed JA3 signatures (ja3_str): 1 UINT16_MAX"
)

# Source the master t2plconf file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
