#!/usr/bin/env bash
#
# Configuration file for voipDetector
# ===================================
#
# Usage
# -----
#
# $ ./t2plconf
#
# Defining the configurations options
# -----------------------------------
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - bitfield
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'bitfield' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for type 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for type 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - bitfield : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - check    : description
#       - radio    : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range    : description ':' min ' ' max
#       - text     : description
#
# Examples
# --------
#
#ITEMS=(
#    # An item can be specified in one line...
#    T2PSKEL_VAR1 check "" "Description of option" # No dependencies
#
#    # Or span multiple lines
#    T2PSKEL_VAR1 radio "T2PSKEL_VAR1 == 1"
#           "Description of option; \
#                   0: description of val 0; \
#                   1: description of val 1; \
#                   2: description of val 2"
#
#    T2PSKEL_SIZE range "T2PSKEL_VAR1 == 1 || T2PSKEL_VAR2 > 0"
#           "Description: 0 255" # min=0, max=255
#
#    T2PSKEL_STR text
#           "T2PSKEL_SIZE <= 5 && (T2PSKEL_VAR1 != 0 || T2PSKEL_VAR2 <= 1)"
#           "Description"
#
#    T2PSKEL_BITFIELD bitfield ""
#           "Description of option; \
#                   0x01: description of bit 0; \
#                   0x02: description of bit 1; \
#                   0x04: description of bit 2; \
#                   0x08: description of bit 3; \
#                   0x10: description of bit 4; \
#                   0x20: description of bit 5; \
#                   0x40: description of bit 6; \
#                   0x80: description of bit 7"
#)
#
# If no configuration option is available, use the value 'none'
#ITEMS=(none)
#
# Source the master t2plconf file
# source ../../scripts/t2conf/t2plconf

ITEMS=(
    VOIP_SIP     radio ""
        "SIP traffic handling; \
            0: Do not decode SIP; \
            1: Enable SIP decoder; \
            2: Decode SIP and add RTP/SIP findex/ssrc flow correlation"
    VOIP_SIP_PRV radio "VOIP_SIP == 2"
        "Enable RTP/SIP flow correalation enhancement; \
            0: No; \
            1: add RTP srcIP; \
            2: add srcIP of SIP flow"
    VOIP_RTP     check "" "Enable RTP decoder"
    VOIP_RTCP    check "" "Enable RTCP decoder"

    VOIP_ANALEN  check "" "Additional check report len against payload length"

    VOIP_SAVE    check ""               "Save RTP content to VOIP_V_PATH"
    VOIP_V_PATH  text  "VOIP_SAVE == 1" "Path for raw VoIP"
    VOIP_FNAME   text  "VOIP_SAVE == 1" "Default content file name prefix"
    VOIP_RMDIR   check "VOIP_SAVE == 1" "Empty VOIP_V_PATH before starting"
    VOIP_BUFMODE check "VOIP_SAVE == 1" "Enable buffering of saved RTP content"
    VOIP_SILREST check "VOIP_SAVE == 1" "Restore back G.711 suppressed silences"
    VOIP_PLDOFF  range "VOIP_SAVE == 1" "Offset for payload to save: 0 255"
    VOIP_MINPKT  range "VOIP_SAVE == 1" "Minimum packet length of a flow: 0 65535"
    VOIP_SVFDX   radio "VOIP_SAVE == 1" "Merge ops; 0: SSRC; 1: findex"

    RTPFMAX      range "VOIP_SVFDX == 0" "Maximal SSRC files: 0 UINT32_MAX"
    RTPBUFSIZE   range "VOIP_SAVE == 1" "Size of the per flow RTP buffer: 0 UINT16_MAX"
    RTPMAXVERS   range "" "Maximal number of version violations: 0 UINT16_MAX"

    SIPNMMAX     range "" "Maximal SIP caller name length: 0 255"
    SIPSTATMAX   range "" "Maximal SIP state requests: 0 255"
    SIPCLMAX     range "" "Maximal SIP state requests name length: 0 255"
    SIPRFXMAX    range "" "Maximal SIP m=audio ports: 0 65535"
)

# Source the master t2plconf file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
