#!/usr/bin/env bash
#
# Configuration file for basicFlow
# ================================
#
# Usage
# -----
#
# $ ./t2plconf
#
# Defining the configurations options
# -----------------------------------
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - bitfield
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'bitfield' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for type 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for type 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - bitfield : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - check    : description
#       - radio    : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range    : description ':' min ' ' max
#       - text     : description
#
# Examples
# --------
#
#ITEMS=(
#    # An item can be specified in one line...
#    T2PSKEL_VAR1 check "" "Description of option" # No dependencies
#
#    # Or span multiple lines
#    T2PSKEL_VAR1 radio "T2PSKEL_VAR1 == 1"
#           "Description of option; \
#                   0: description of val 0; \
#                   1: description of val 1; \
#                   2: description of val 2"
#
#    T2PSKEL_SIZE range "T2PSKEL_VAR1 == 1 || T2PSKEL_VAR2 > 0"
#           "Description: 0 255" # min=0, max=255
#
#    T2PSKEL_STR text
#           "T2PSKEL_SIZE <= 5 && (T2PSKEL_VAR1 != 0 || T2PSKEL_VAR2 <= 1)"
#           "Description"
#
#    T2PSKEL_BITFIELD bitfield ""
#           "Description of option; \
#                   0x01: description of bit 0; \
#                   0x02: description of bit 1; \
#                   0x04: description of bit 2; \
#                   0x08: description of bit 3; \
#                   0x10: description of bit 4; \
#                   0x20: description of bit 5; \
#                   0x40: description of bit 6; \
#                   0x80: description of bit 7"
#)
#
# If no configuration option is available, use the value 'none'
#ITEMS=(none)
#
# Source the master t2plconf file
# source ../../scripts/t2conf/t2plconf

ITEMS=(
    BFO_SENSORID       check "" "Output sensor ID"
    BFO_HDRDESC_PKTCNT check "" "Enable packet count for header description"
    BFO_MAC            check "" "Enable MAC addresses output"
    BFO_ETHERTYPE      check "" "Enable EtherType output"

    BFO_MPLS radio ""
        "MPLS handling; \
            0: Do not output MPLS information; \
            1: Output MPLS labels; \
            2: Output MPLS labels as hex; \
            3: Output MPLS headers as hex; \
            4: Output decoded MPLS headers as label_ToS_S_TTL"

    BFO_VLAN radio ""
        "VLANs handling; \
            0: Do not output VLAN information; \
            1: Output VLAN numbers; \
            2: Output VLAN headers as hex; \
            3: Output decoded VLAN headers"

    #BFO_GTP    check "" "Enable GTP output"
    BFO_GRE    check "" "Enable GRE output"
    BFO_L2TP   check "" "Enable L2TP output"
    BFO_PPP    check "" "Enable PPP output"
    BFO_LAPD   check "" "Enable LAPD output"
    BFO_TEREDO check "" "Enable Teredo output"

    BFO_SUBNET_IPLIST radio ""
        "; \
            0: Display only the IP masked by {SRC,DST}IP[46]CMSK; \
            1: Display a list of IP aggregated"

    BFO_SUBNET_TEST        check "" "Enable subnet test"
    BFO_SUBNET_TEST_GRE    check "" "Enable subnet test on GRE addresses"
    BFO_SUBNET_TEST_L2TP   check "" "Enable subnet test on L2TP addresses"
    BFO_SUBNET_TEST_TEREDO check "" "Enable subnet test on Teredo addresses"

    BFO_SUBNET_ASN check
            "BFO_SUBNET_TEST == 1 || BFO_SUBNET_TEST_GRE == 1 || BFO_SUBNET_TEST_L2TP == 1 || BFO_SUBNET_TEST_TEREDO == 1"
            "Output Autonomous System Numbers (ASN)"
    BFO_SUBNET_LL check
            "BFO_SUBNET_TEST == 1 || BFO_SUBNET_TEST_GRE == 1 || BFO_SUBNET_TEST_L2TP == 1 || BFO_SUBNET_TEST_TEREDO == 1"
            "Output position (latitude, longitude and reliability)"
    BFO_SUBNET_ORG check
            "BFO_SUBNET_TEST == 1 || BFO_SUBNET_TEST_GRE == 1 || BFO_SUBNET_TEST_L2TP == 1 || BFO_SUBNET_TEST_TEREDO == 1"
            "Output organization"
    BFO_SUBNET_HEX check
            "BFO_SUBNET_TEST == 1 || BFO_SUBNET_TEST_GRE == 1 || BFO_SUBNET_TEST_L2TP == 1 || BFO_SUBNET_TEST_TEREDO == 1"
            "Output country and organization info. as hexadecimal"

    BFO_MAX_HDRDESC range ""                       "Maximum number of headers descriptions to store: 0 255"
    BFO_MAX_MAC     range "BFO_MAC == 1"           "Maximum number of different MAC addresses: 0 255"
    BFO_MAX_IP      range "BFO_SUBNET_IPLIST == 1" "Maximum number of different IP addresses: 1 255"
    BFO_MAX_MPLS    range "BFO_MPLS > 0"           "Maximum MPLS headers/tags to store: 0 255"
    BFO_MAX_VLAN    range "BFO_VLAN > 0"           "Maximum VLAN headers/numbers to store: 0 255"
)

# Source the master t2plconf file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
