#!/usr/bin/env bash
#
# Configuration file for tcpFlags
# ===============================
#
# Usage
# -----
#
# $ ./t2plconf
#
# Defining the configurations options
# -----------------------------------
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - bitfield
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'bitfield' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for type 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for type 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - bitfield : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - check    : description
#       - radio    : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range    : description ':' min ' ' max
#       - text     : description
#
# Examples
# --------
#
#ITEMS=(
#    # An item can be specified in one line...
#    T2PSKEL_VAR1 check "" "Description of option" # No dependencies
#
#    # Or span multiple lines
#    T2PSKEL_VAR1 radio "T2PSKEL_VAR1 == 1"
#           "Description of option; \
#                   0: description of val 0; \
#                   1: description of val 1; \
#                   2: description of val 2"
#
#    T2PSKEL_SIZE range "T2PSKEL_VAR1 == 1 || T2PSKEL_VAR2 > 0"
#           "Description: 0 255" # min=0, max=255
#
#    T2PSKEL_STR text
#           "T2PSKEL_SIZE <= 5 && (T2PSKEL_VAR1 != 0 || T2PSKEL_VAR2 <= 1)"
#           "Description"
#
#    T2PSKEL_BITFIELD bitfield ""
#           "Description of option; \
#                   0x01: description of bit 0; \
#                   0x02: description of bit 1; \
#                   0x04: description of bit 2; \
#                   0x08: description of bit 3; \
#                   0x10: description of bit 4; \
#                   0x20: description of bit 5; \
#                   0x40: description of bit 6; \
#                   0x80: description of bit 7"
#)
#
# If no configuration option is available, use the value 'none'
#ITEMS=(none)
#
# Source the master t2plconf file
# source ../../scripts/t2conf/t2plconf

ITEMS=(
    SPKTMD_SEQACKREL radio ""
        "SEQ/ACK numbers representation (-s option); \
            0: absolute; \
            1: relative"

    SPKTMD_SEQACKHEX radio ""
        "SEQ/ACK numbers representation (-s option); \
            0: uint32_t; \
            1: hex32"

    IPCHECKSUM radio ""
        "; \
            0: No checksum calculation; \
            1: Calculation of L3 (IP) header checksum; \
            2: L3+L4 (TCP, UDP) checksum"

    IPTOS radio ""
        "IPv4 Type of Service / IPv6 Class representation; \
            0: IP ToS hex; \
            1: DSCP_ECN decimal; \
            2: Precedence(1-7)_ECN decimal"

    RTT_ESTIMATE  check "" "Round trip time estimation"
    WINDOWSIZE    check "" "Calculation of TCP window size parameters"
    WINMIN        range "" "Minimal window size threshold defining a healthy communication: 0 UINT16_MAX"
    SEQ_ACK_NUM   check "" "Seq/Ack number feature analysis"
    FRAG_ANALYZE  check "" "Fragmentation analysis"
    NAT_BT_EST    check "" "NAT boot time estimation"
    SCAN_DETECTOR check "" "Scan flow detector"
    MPTCP         check "" "Dissect Multipath TCP (MPTCP)"
    TCPFLGCNT     check "" "TCP flags counts"
    TCPJA4T       check "" "Output JA4T/JA4TS fingerprints"
    JA4TOPTMX range "TCPJA4T == 1" "Maximal options stored in flow"
)

# Source the master t2plconf file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
