#!/usr/bin/env bash

source "$(dirname "${0}")/../../t2utils.sh"

OPTS=()
while [[ "${#}" -ne 0 ]]; do
    case "${1}" in
        -n)
            validate_next_int "${1}" "${2}"
            N="${2}"
            shift
            ;;
        *)
            OPTS+=("${1}")
            ;;
    esac
    shift
done

nfdump ${OPTS[@]} -I | "${TAWK}" -F: '
    $1 == "First"      { sec  = chomp($2); next }
    $1 == "msec_first" { msec = chomp($2); exit }
    END {
        print sec "." msec
    }'
