#!/usr/bin/env bash

source "$(dirname "${0}")/../../t2utils.sh"

OPTS=()
while [[ "${#}" -ne 0 ]]; do
    case "${1}" in
        -n)
            validate_next_int "${1}" "${2}"
            N="${2}"
            shift
            ;;
        *)
            OPTS+=("${1}")
            ;;
    esac
    shift
done

nfdump ${OPTS[@]} -s 'srcip/packets' | "${TAWK}" -F, -v n="${N}" '
    NF > 1 && NR > 1 {
        aggr(unquote(t2whois($5, "org")), $8, n)
    }'
