#!/usr/bin/env bash
#
# Configuration file for sshDecode
# ================================
#
# Usage
# -----
#
# $ ./t2plconf
#
# Defining the configurations options
# -----------------------------------
#
# If no configuration options are available, ITEMS must be set as follows:
#   - ITEMS=(none)
#
# Otherwise, enter configurations items as follows:
#   "NAME" "TYPE" "DEPENDENCIES" "DESCRIPTION"
#
#   - TYPE can be:
#       - bitfield
#       - check (boolean),
#       - radio (set of values),
#       - range (min <= val <= max)
#       - text
#
#   - DEPENDENCIES MUST be numeric, e.g., "A == 1 && (B < 4 || C >= 1)"
#
#   - DESCRIPTION for type 'bitfield' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'check' MUST NOT contain tabs ('\t')
#   - DESCRIPTION for type 'radio' MUST NOT contain '\t', ':' or ';'
#   - DESCRIPTION for type 'range' MUST NOT contain '\t' or ':'
#   - DESCRIPTION for type 'text'  MUST NOT contain '\t'
#
#   - DESCRIPTION MUST be formatted according to the type (see examples below):
#       - bitfield : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - check    : description
#       - radio    : description ';' val1 ':' description1 ';' valN ':' descriptionN
#       - range    : description ':' min ' ' max
#       - text     : description
#
# Examples
# --------
#
#ITEMS=(
#    # An item can be specified in one line...
#    T2PSKEL_VAR1 check "" "Description of option" # No dependencies
#
#    # Or span multiple lines
#    T2PSKEL_VAR1 radio "T2PSKEL_VAR1 == 1"
#           "Description of option; \
#                   0: description of val 0; \
#                   1: description of val 1; \
#                   2: description of val 2"
#
#    T2PSKEL_SIZE range "T2PSKEL_VAR1 == 1 || T2PSKEL_VAR2 > 0"
#           "Description: 0 255" # min=0, max=255
#
#    T2PSKEL_STR text
#           "T2PSKEL_SIZE <= 5 && (T2PSKEL_VAR1 != 0 || T2PSKEL_VAR2 <= 1)"
#           "Description"
#
#    T2PSKEL_BITFIELD bitfield ""
#           "Description of option; \
#                   0x01: description of bit 0; \
#                   0x02: description of bit 1; \
#                   0x04: description of bit 2; \
#                   0x08: description of bit 3; \
#                   0x10: description of bit 4; \
#                   0x20: description of bit 5; \
#                   0x40: description of bit 6; \
#                   0x80: description of bit 7"
#)
#
# If no configuration option is available, use the value 'none'
#ITEMS=(none)
#
# Source the master t2plconf file
# source ../../scripts/t2conf/t2plconf

ITEMS=(
    SSH_USE_PORT check "" "Count all packets to/from port SSH_PORT as SSH"
    SSH_DECODE radio "" "; \
            0: Do not decode SSH handshake messages; \
            1: Only decode SSH Key Exchange Init messages; \
            2: Decode all SSH Exchange messages"

    SSH_FINGERPRINT radio "SSH_DECODE == 2"
            "Algorithm to use for the fingerprint; \
                0: No fingerprint; \
                1: MD5; \
                2: SHA256"

    SSH_ALGO  check "SSH_DECODE > 0" "Output chosen algorithms"
    SSH_LISTS check "SSH_DECODE > 0" "Output lists of supported algorithms"

    SSH_HASSH check "" "Output HASSH fingerprint (hash and description)"
    SSH_HASSH_STR check "SSH_HASSH == 1"
            "Output HASSH fingerprint before hashing"
    SSH_HASSH_DLEN range "SSH_HASSH == 1"
            "Max length for HASSH descriptions: 0: 1024"
    SSH_HASSH_STR_LEN range "SSH_HASSH == 1"
            "Max length for uncompressed HASSH signatures: 0: 2048"
    SSH_HASSH_NAME text  "SSH_HASSH == 1"
            "Name of the HASSH database"

    SSH_BUF_SIZE range "" "Max length for strings: 1 UINT16_MAX"
    SSH_HKT_SIZE range "SSH_DECODE > 0" "Max length for host key type and chosen algorithms: 1 UINT16_MAX"

    SSH_DEBUG check "" "Activate debug output"
)

# Source the master t2plconf file
source "$(dirname "$0")/../../scripts/t2conf/t2plconf"
